In [1]:
import numpy as np

In [2]:
a = np.array([10,20,30,40,50,60,70])
b = np.array([1,2,3,4,5,6,7])
a,b

(array([10, 20, 30, 40, 50, 60, 70]), array([1, 2, 3, 4, 5, 6, 7]))

In [3]:
a+b

array([11, 22, 33, 44, 55, 66, 77])

In [4]:
a*b

array([ 10,  40,  90, 160, 250, 360, 490])

In [5]:
a*2

array([ 20,  40,  60,  80, 100, 120, 140])

In [6]:
a**3

array([  1000,   8000,  27000,  64000, 125000, 216000, 343000],
      dtype=int32)

In [7]:
b*= 5
b

array([ 5, 10, 15, 20, 25, 30, 35])

In [8]:
b = b / 3
b

array([ 1.66666667,  3.33333333,  5.        ,  6.66666667,  8.33333333,
       10.        , 11.66666667])

In [19]:
arr1 = np.array([[1,2,3]])
arr1
arr1.shape

(1, 3)

In [20]:
arr2 = arr1.T; #transpose()
arr2
arr2.shape

(3, 1)

In [21]:
arr3 = arr1 + arr2
arr3

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [22]:
arr1 * arr2


array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [23]:
np.dot(arr1, arr2)

array([[14]])

In [27]:
np.random.seed(0)
arr = np.random.randint(-10, 10, (7,8))
arr

array([[  2,   5, -10,  -7,  -7,  -3,  -1,   9],
       [  8,  -6,  -4,   2,  -9,  -4,  -3,   4],
       [  7,  -5,   3,  -2,  -1,   9,   6,   9],
       [ -5,   5,   5, -10,   8,  -7,   7,   9],
       [  9,   9,   4,  -3, -10,  -9,  -1, -10],
       [  0,  -7,   1,   8,  -8, -10, -10,  -6],
       [ -5,  -4,  -2,   7,   5,  -6,  -1,   0]])

In [28]:
arr[6], arr[-1]

(array([-5, -4, -2,  7,  5, -6, -1,  0]),
 array([-5, -4, -2,  7,  5, -6, -1,  0]))

In [29]:
# wiersz nr 2 i 3 oraz co 2-ga kolumna
arr[ 1:3 , ::2 ]

array([[ 8, -4, -9, -3],
       [ 7,  3, -1,  6]])

In [30]:
# tylko pierwszy i ostatni wiersz
arr[ [0,-1] ]

array([[  2,   5, -10,  -7,  -7,  -3,  -1,   9],
       [ -5,  -4,  -2,   7,   5,  -6,  -1,   0]])

In [31]:
arr

array([[  2,   5, -10,  -7,  -7,  -3,  -1,   9],
       [  8,  -6,  -4,   2,  -9,  -4,  -3,   4],
       [  7,  -5,   3,  -2,  -1,   9,   6,   9],
       [ -5,   5,   5, -10,   8,  -7,   7,   9],
       [  9,   9,   4,  -3, -10,  -9,  -1, -10],
       [  0,  -7,   1,   8,  -8, -10, -10,  -6],
       [ -5,  -4,  -2,   7,   5,  -6,  -1,   0]])

In [32]:
arr.T[-1]

array([  9,   4,   9,   9, -10,  -6,   0])

In [33]:
# tylko kolumna 2 i przedostatnia
arr[ : , [1,-2]]

array([[  5,  -1],
       [ -6,  -3],
       [ -5,   6],
       [  5,   7],
       [  9,  -1],
       [ -7, -10],
       [ -4,  -1]])

In [35]:
arr[-1,-1]

0

In [36]:
arr

array([[  2,   5, -10,  -7,  -7,  -3,  -1,   9],
       [  8,  -6,  -4,   2,  -9,  -4,  -3,   4],
       [  7,  -5,   3,  -2,  -1,   9,   6,   9],
       [ -5,   5,   5, -10,   8,  -7,   7,   9],
       [  9,   9,   4,  -3, -10,  -9,  -1, -10],
       [  0,  -7,   1,   8,  -8, -10, -10,  -6],
       [ -5,  -4,  -2,   7,   5,  -6,  -1,   0]])

In [37]:
for row in arr:
    print(row)
    print("="*60)

[  2   5 -10  -7  -7  -3  -1   9]
[ 8 -6 -4  2 -9 -4 -3  4]
[ 7 -5  3 -2 -1  9  6  9]
[ -5   5   5 -10   8  -7   7   9]
[  9   9   4  -3 -10  -9  -1 -10]
[  0  -7   1   8  -8 -10 -10  -6]
[-5 -4 -2  7  5 -6 -1  0]


In [38]:
lista1 = [1,2,3,4]
lista2 = lista1

In [40]:
lista2[0] = -999

In [41]:
lista1

[-999, 2, 3, 4]

In [42]:
lista1 = [1,2,3,4]
lista2 = lista1.copy()

In [43]:
lista2[0] = -999
lista1, lista2

([1, 2, 3, 4], [-999, 2, 3, 4])

In [44]:
arr2 = arr # to nie jest klonowanie tablicy

In [45]:
arr2 = np.copy(arr)

In [46]:
id(arr), id(arr2)

(2125849287248, 2125837218896)

### Porownanie szybkosci list vs numpy

In [47]:
%%timeit -r 10 -n 100
[x**2 for x in range(10_000)]

2.41 ms ± 86.9 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)


In [49]:
%%timeit -r 10 -n 100
np.arange(10_000)**2

18.9 µs ± 7.38 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)


In [50]:
2.41E-3 / 18.9E-6

127.51322751322752