In [1]:
import numpy as np

In [2]:
# klasyczne filtrowanie
numbers_list = [-1, 10, 15, 200, -200, 1000, 667, 997]

In [3]:
[x for x in numbers_list if x>0]

[10, 15, 200, 1000, 667, 997]

In [6]:
def only_positive(x):
    return x>0

list(filter(only_positive, numbers_list ))

[10, 15, 200, 1000, 667, 997]

In [7]:
list(filter(lambda x: x>0 , numbers_list ))

[10, 15, 200, 1000, 667, 997]

In [8]:
arr = np.array(numbers_list)
arr

array([  -1,   10,   15,  200, -200, 1000,  667,  997])

In [10]:
arr[arr>0]

array([  10,   15,  200, 1000,  667,  997])

In [11]:
list(filter(lambda x: x>0 and x<100 , numbers_list ))

[10, 15]

In [13]:
arr[(arr>0)&(arr<100)]

array([10, 15])

In [17]:
# < 0 lub > 100
list( filter( lambda x: x<0 or x>100, numbers_list))

[-1, 200, -200, 1000, 667, 997]

In [20]:
arr[ (arr<0)|(arr>100)]

array([  -1,  200, -200, 1000,  667,  997])

In [21]:
arr = np.array([-1, 3, 4, np.NaN, 5, 6, np.NaN])
arr

array([-1.,  3.,  4., nan,  5.,  6., nan])

In [22]:
arr.sum()

nan

In [26]:
arr[~np.isnan(arr)].sum()

17.0

In [27]:
np.sum(arr[~np.isnan(arr)].sum())

17.0

In [30]:
np.isnan(arr).all()

False

In [31]:
s = "Ala ma kota"
s[::-1]

'atok am alA'